# An example of ClusterConfig with KMS envelope encryption for all kubernetes data with a CMK
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-45
  region: us-west-2
  # Only available on k8s 1.28+
  version: '1.28'
managedNodeGroups:
- name: ng-1
  desiredCapacity: 2
kubernetesDataEncryption:
  # ARN of the KMS key
  keyARN: "arn:aws:kms:us-west-2:000000000000:key/00000000-0000-0000-0000-000000000000"